fix: Add missing `unwrap` on `device.sysname()`
```rust
error[E0599]: no method named `to_str` found for enum `Option` in the current scope
   --> src/config.rs:189:41
    |
189 |             let name = device.sysname().to_str().ok_or("Failed to convert from ffi::OsStr to &str");
    |                                         ^^^^^^ method not found in `Option<&OsStr>`
```